ALTER SEQUENCE point_sequence RESTART WITH 200;
ALTER SEQUENCE point_event_sequence RESTART WITH 200;
ALTER SEQUENCE point_name_sequence RESTART WITH 200;
ALTER SEQUENCE vendor_sequence RESTART WITH 200;
ALTER SEQUENCE list_sequence RESTART WITH 200;
ALTER SEQUENCE tag_sequence RESTART WITH 200;
ALTER SEQUENCE report_sequence RESTART WITH 200;
ALTER SEQUENCE pointlist_sequence RESTART WITH 200;
ALTER SEQUENCE device_sequence RESTART WITH 200;
ALTER SEQUENCE users_sequence RESTART WITH 200;
ALTER SEQUENCE client_sequence RESTART WITH 200;
ALTER SEQUENCE client_event_sequence RESTART WITH 200;

